name: Deploy

on:
    push:
        branches:
        - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up google cloud credentials
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Deploy
        run: |
          cd /GestaoEventos && git pull origin main && sudo docker stop $(sudo docker ps -a -q)
          && sudo docker system prune -f && sudo docker build -t gestao-eventos .
          && sudo docker run -d -p 80:80 gestao-eventos
